# ~/.config/starship.toml
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Change the default prompt format
format = """\
($cmd_duration\n)\
[╭╴](238)$env_var$username$directory $git_branch $git_status $fill$all\
[╰─](238)$character\
"""

continuation_prompt = "[\ue602 \ue602](238)"

command_timeout = 1_000_000

# Set 'foo' as custom color palette
# palette = 'foo'

# Define custom colors
# [palettes.foo]
# grey = '238'
# green = '034'
# orange = '208'
# blue = '111'
# red = '160'
# beige = '011'

[fill]
symbol = ' '

[cmd_duration]
min_time = 500
format = "[\uf017 $duration](bold 011)"

# Change the default prompt characters
[character]
success_symbol = "[\ue602](238)"
error_symbol = "[\ue602](238)"

# Shows an icon that should be included by zshrc script based on the distribution or os
[env_var.STARSHIP_DISTRO]
format = '[$env_value](bold 111)'  # removed space between distro and rest for pwsh
variable = "STARSHIP_DISTRO"
disabled = false

# Shows the username
[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = false  # disable in powershell
show_always = false

[directory]
truncation_length = 3
truncation_symbol = "…/"
home_symbol = "\uf015 ~"
style = "bold 135"
read_only_style = "197"
read_only = " \ue0a2 "
format = "at [$path]($style)[$read_only]($read_only_style)"

[git_branch]
symbol = "\uf418 "
format = "on [$symbol$branch]($style)"
# truncation_length = 10
# truncation_symbol = "…/"
style = "bold 034"

[git_status]
format = """\
$ahead_behind \
([\\(\
[$conflicted](160)\
[$stashed](238)\
[$deleted](160)\
[$renamed](011)\
[$modified](208)\
[$staged](111)\
[$untracked](011) \
\\)]($style))"""
style = "bold 034"
up_to_date = "[\uf00c](034)"
ahead = "[⇡${count}](208)"
diverged = "[⇕⇡${ahead_count}⇣${behind_count}](208)"
conflicted = " 🏳${count}"
untracked = " \uec0c${count}"
behind = "[⇣${count}](208)"
stashed = " \uf187${count}"
modified = " \ueb43${count}"
staged = '++${count}'
renamed = " T${count}"
deleted = " \uea81${count}"

[terraform]
format = "via [\ue8bd terraform $version]($style) 壟 [$workspace]($style)"

[vagrant]
format = "via [\ue8d0 vagrant $version]($style)"

[docker_context]
format = "via [\uf21f $context](bold 111)"

[helm]
format = "via [\ue7fb $version](bold purple)"

[python]
symbol = "\ue73c "
python_binary = "python3"

[nodejs]
format = "[\ued0d $version](bold 070)"
# disabled = true

[package]
format = "[\uf487 $version](bold 208)"
disabled = true

[ruby]
format = "[\ue23e $version]($style)"

[kubernetes]
format = 'on [\ue81d $context\($namespace\)](bold purple)'
disabled = false
[kubernetes.context_aliases]
"clcreative-k8s-staging" = "cl-k8s-staging"
"clcreative-k8s-production" = "cl-k8s-prod"